driverPath: ./src/test/resources/chromedriver.exe/
baseUrl: https://magento.softwaretestingboard.com
baseUrlAPI: https://thinking-tester-contact-list.herokuapp.com
baseUrlBNM: https://bnm.md/en/official_exchange_rates?get_xml=1&date=